# Generated by Django 4.2.10 on 2024-02-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='pay_method',
            field=models.CharField(default='bkash', max_length=10),
        ),
        migrations.AddField(
            model_name='donation',
            name='trx_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
